# Site settings
title: rook.io
url: "https://rook.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-93639004-1

# Build settings
markdown: kramdown

# plugins
# NOTE: github pages ignores custom plugins and any other plugin which is not whitelisted
# SEE: https://pages.github.com/versions/
plugins:
  - jekyll-relative-links
  - jekyll-babel
  - jekyll-readme-index

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - build

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      title: "Rook"
  -
    scope:
      path: "docs/rook"
    values:
      layout: "docs"
      doctitle: "Rook Docs"
      github: "https://github.com/rook/rook/blob/master/Documentation/"
      stylesheet: "docs"

sass:
  sass_dir: ./_scss

current_release_index: 1
