name: Build and Publish Website

on:
  push:
    branches:
      - master

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

permissions:
  contents: read

jobs:
  build-and-publish-website:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build and publish website
        run: |
          make publish

      - name: Set up tmate session for debugging
        if: failure()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
